--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

create table public.animals (
    id bigint generated by default as identity primary key,
    name text not null,
    species text not null,
    breed text,
    date_of_birth timestamp with time zone,
    weight_kg numeric(6,2),
    microchip_number text,
    status text not null default 'active',
    owner_id bigint not null
);

create table public.consultations (
    id bigint generated by default as identity primary key,
    animal_id bigint not null,
    date timestamp with time zone not null,
    reason text not null,
    diagnosis text,
    treatment text,
    next_appointment timestamp with time zone,
    attachments jsonb[] default '{}'::jsonb[]
);

create table public.vaccinations (
    id bigint generated by default as identity primary key,
    animal_id bigint not null,
    vaccine_name text not null,
    administered_on date not null,
    validity_months integer not null check (validity_months > 0)
);

--
-- Foreign keys
--

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.animals
    add constraint animals_owner_id_fkey foreign key (owner_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.consultations
    add constraint consultations_animal_id_fkey foreign key (animal_id) references public.animals(id) on update cascade on delete cascade;

alter table public.vaccinations
    add constraint vaccinations_animal_id_fkey foreign key (animal_id) references public.animals(id) on update cascade on delete cascade;

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);

create index animals_owner_id_idx on public.animals using btree (owner_id);

create index consultations_animal_id_idx on public.consultations using btree (animal_id);

create index vaccinations_animal_id_idx on public.vaccinations using btree (animal_id);
